version: "3.8"

services:
  zookeeper:
    container_name: zookeeper
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  jupyterlab:
    container_name: jupyterlab
    build:
      context: jupyterlab/
      dockerfile: Dockerfile
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - RESTARTABLE=yes
    ports:
      - 8888:8888
    volumes:
      - $PWD/notebooks:/home/jovyan
    entrypoint: ["start.sh", "jupyter", "lab", "--LabApp.token=''"]

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
